apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: hangar
  labels:
    hangar-service: backend
spec:
  ports:
    - port: 8080
      name: backend
  selector:
    hangar-service: backend
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend
  namespace: hangar
  labels:
    hangar-service: backend
spec:
  serviceName: "backend"
  replicas: 1
  selector:
    matchLabels:
      hangar-service: backend
  template:
    metadata:
      labels:
        hangar-network: "true"
        hangar-service: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/papermc/hangar_backend
          env:
            {{- range $key, $value := .Values.env.backend }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          stdin: true
          volumeMounts:
            - mountPath: /hangar/uploads
              name: hangar-data
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
      restartPolicy: Always
      volumes:
        - name: hangar-data
          persistentVolumeClaim:
            claimName: hangar-data
  volumeClaimTemplates:
    - metadata:
        name: hangar-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
