apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: hangar
  labels:
    hangar-service: frontend
spec:
  ports:
    - port: 1337
      name: frontend
  selector:
    hangar-service: frontend
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: frontend
  namespace: hangar
  labels:
    hangar-service: frontend
spec:
  serviceName: "frontend"
  replicas: 1
  selector:
    matchLabels:
      hangar-service: frontend
  template:
    metadata:
      labels:
        hangar-service: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/papermc/hangar_frontend
          env:
            {{- range $key, $value := .Values.env.backend }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          stdin: true
          # todo better probes
          readinessProbe:
            httpGet:
              path: /
              port: 1337
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 1337
            initialDelaySeconds: 60
            periodSeconds: 60
      restartPolicy: Always
