apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    hangar-service: ingress
  name: hangar
  namespace: hangar
spec:
  rules:
    - host: {{ .Values.ingressHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 1337
