version: '3.7'

services:
  postgres:
    build: ./postgres
    environment:
      POSTGRES_MULTIPLE_DATABASES: hydra,kratos
      POSTGRES_DB: hangar
      POSTGRES_USER: hangar
      POSTGRES_PASSWORD: 'hangar'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

networks:
  default:
    name: hangar-network
