version: '3.7'

services:
  app:
    image: registry.gitlab.com/minidigger/hangar2/app:latest
    build:
      context: ..
      dockerfile: docker/hangar/Dockerfile
    ports:
    - "8080:8080"
    - "5005:5005"
    volumes:
    - ../:/app
    - uploads:/uploads
    working_dir: /app
    depends_on:
      - 'db'
#      - 'auth'
      - 'mail'
    stdin_open: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.hangarnew.loadbalancer.server.port=8080"
      - "traefik.http.routers.hangarnew.rule=Host(`hangar.benndorf.dev`)"
      - "traefik.http.routers.hangarnew.entrypoints=web-secure"
      - "traefik.http.routers.hangarnew.tls=true"
      - "traefik.http.routers.hangarnew.tls.options=default"
      - "traefik.http.routers.hangarnew.tls.certresolver=default"
      - "traefik.http.routers.hangarnew.tls.domains[0].main=benndorf.dev"
      - "traefik.http.routers.hangarnew.tls.domains[0].sans=*.benndorf.dev"
    networks:
      - web
    user: appuser
    command: './mvnw spring-boot:run -Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Dspring-boot.run.arguments=--spring.config.location="./docker/hangar/application.yml"'
  db:
    image: registry.gitlab.com/minidigger/hangar2/db:latest
    build: ./db
    environment:
      POSTGRES_MULTIPLE_DATABASES: hangarauth
      POSTGRES_DB: hangar
      POSTGRES_USER: hangar
      POSTGRES_PASSWORD: hangar
    ports:
      - "2345:5432" # pls dont abuse open port :/
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - web
    labels:
      - "traefik.enable=false"
  mail:
    image: mailhog/mailhog:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.hangar-mail.loadbalancer.server.port=8025"
      - "traefik.http.routers.hangar-mail.middlewares=basicauth@file"
      - "traefik.http.routers.hangar-mail.rule=Host(`hangar-mail.benndorf.dev`)"
      - "traefik.http.routers.hangar-mail.entrypoints=web-secure"
      - "traefik.http.routers.hangar-mail.tls=true"
      - "traefik.http.routers.hangar-mail.tls.options=default"
      - "traefik.http.routers.hangar-mail.tls.certresolver=default"
      - "traefik.http.routers.hangar-mail.tls.domains[0].main=benndorf.dev"
      - "traefik.http.routers.hangar-mail.tls.domains[0].sans=*.benndorf.dev"
    networks:
      - web
    ports:
      - "8025:8025"
      - "1025:1025"

networks:
  web:
    name: traefik-overlay
    external: true

volumes:
  db_data:
  uploads:
  public_html:
