spring:
  datasource:
    url: jdbc:postgresql://db:5432/hangar
    username: hangar
    password: hangar

fake-user:
  enabled: false

hangar:
  dev: true
  base-url: "http://localhost:3000"

  discourse:
    enabled: false
    url: "http://localhost:80/"
    admin-user: "admin"


logging:
  level:
    #    root: TRACE
    io:
      papermc:
        hangar:
          config:
            jackson: DEBUG
