spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/hangar
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"

fake-user:
  enabled: false

hangar:
  dev: false
  base-url: "https://hangar.benndorf.dev"
  plugin-upload-dir: "/hangar/uploads"

  announcements:
    -
      text: "This is a staging server for testing purposes. Data could be deleted at any time. That said, signups are open, please test stuff and report and feedback on github or discord!"
      color: "#ff544b"

  sso:
    auth-url: "https://hangar-auth.benndorf.dev"
    oauth-url: "https://hangar-auth.benndorf.dev/hydra"
    client-id: "${SSO_CLIENT_ID}"
    api-key: "${SSO_SECRET}"

  security:
    api:
      url: "https://hangar-auth.benndorf.dev"
      avatar-url: "https://hangar-auth.benndorf.dev/avatar/%s"
    token-secret: "${TOKEN_SECRET}"
    image-proxy-url: "https://hangar-auth.benndorf.dev/image/%s"

logging:
  level:
    root: INFO
    org.springframework: INFO
