name: Build

on:
  # allow manual dispatch
  workflow_dispatch:
  # run on PRs
  pull_request:
    branches:
    - nuxt-frontend
    #- master TODO: once nuxt is merged, change this back

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Build backend
        run: mvn install

      - name: Install frontend deps
        run: (cd frontend && yarn)

      - name: Build frontend
        run: (cd frontend && yarn build)
