name: Dummy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: DUMMY
        run: |
          echo POSTGRES_USER
          echo ${{secrets.POSTGRES_USER}} | sed 's/./& /g'
          echo POSTGRES_PASSWORD
          echo ${{secrets.POSTGRES_PASSWORD}} | sed 's/./& /g'
